spring:
  datasource:
    url: jdbc:mysql://47.106.116.128:3306/activiti?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update

server:
  port: 8080
flowable:
  async-executor-activate: false